add the organisational header variant
nhsuk/wagtail-nhsuk-frontend pull request #168
Opened 2020-04-15 17:31 UTC by AdamChrimes

- Ability to use the organisation header with organisation name and descriptor and the white variant.
- Ability to upload a custom logo to replace the default NHS logo, which can be used for organisation logos.
- Reorganised some of the admin layout to be clearer and organised.

To do:

- [ ] Add the organisation split element, to split larger organisation names
- [ ] Review admin layout and settings to make it simpler eg. can't use a service header and a organisational header at same time. 
- [ ] Make the if statements cleaner
- [ ] Test different settings variations

2021-05-10 13:18 UTC, DomBaker commented
Fixed it for you @chrimesdev 😉

2021-05-10 14:01 UTC, mikemonteith requested changes
Left comments inline.
Also need to update the documentation at [./docs/components/header.md](https://github.com/nhsuk/wagtail-nhsuk-frontend/blob/master/docs/components/header.md)

2021-05-10 15:53 UTC, DomBaker commented on wagtailnhsukfrontend/settings/migrations/0009_merge_0006and0008.py
> +# Generated by Django 3.1.8 on 2021-05-10 13:09
Fixed this issue.

2021-05-11 10:33 UTC, mikemonteith commented on wagtailnhsukfrontend/settings/models.py
> +        Image,
According to the docs, wagtail plugins should always use `get_image_model()`

2021-05-17 13:52 UTC, DomBaker commented on wagtailnhsukfrontend/settings/models.py
> +    organisation_name = models.CharField(max_length=255, blank=True)
Added some help text for both of the queried fields, took the information from the service manual.

2021-05-17 13:53 UTC, DomBaker commented on wagtailnhsukfrontend/settings/models.py
> +        Image,
updated.

2021-05-20 15:29 UTC, mikemonteith approved these changes

2021-05-20 15:37 UTC, merged

2021-05-20 15:59 UTC, damonjagger commented
🔥