prepare for v1.0.0
nhsuk/wagtail-nhsuk-frontend pull request #210
Opened 2021-08-09 12:33 UTC by magicaljellybeans

2021-08-10 10:31 UTC, mikemonteith commented on README.md
> +## Upgrading
I don't think this "upgrading" is necessary in the readme. Having notes in the changelog should be enough.
Maybe a small section that says "If you are using v0 and wish to upgrade to v1, see the changelog" with a link to the changelog "upgrade considerations" notes.

2021-08-10 10:47 UTC, mikemonteith commented on CHANGELOG.md
> +- Panel Block, Panel List, Grey Panel Block, Promo Block, Promo Group Block have been removed from the plugin, so references to these in your project will need to be removed in order to upgrade. Ensu
We should probably refer to these blocks by their python class name (`PanelBlock`, `PanelList` etc.)

2021-08-11 09:02 UTC, mikemonteith requested changes

2021-08-11 09:29 UTC, dragon-dxw commented on CHANGELOG.md
> +- `PanelBlock`, `PanelList`, `GreyPanelBlock`, `PromoBlock`, `PromoGroupBlock` have been removed from the plugin, so references to these in your project will need to be removed in order to upgrade. E
I'd certainly appreciate advice on the recommended way of transferring content currently in deprecated blocks: which fields should we remap to which blocks for the best user experience?

2021-08-11 13:15 UTC, magicaljellybeans commented on CHANGELOG.md
> +- `PanelBlock`, `PanelList`, `GreyPanelBlock`, `PromoBlock`, `PromoGroupBlock` have been removed from the plugin, so references to these in your project will need to be removed in order to upgrade. E
@dragon-dxw I've updated the changelog with some more information - does this tell you everything you need to know?

2021-08-11 16:54 UTC, dragon-dxw commented on CHANGELOG.md
> +- `PanelBlock`, `PanelList`, `GreyPanelBlock`, `PromoBlock`, `PromoGroupBlock` have been removed from the plugin, so references to these in your project will need to be removed in order to upgrade. E
Haven't used it in anger yet, but that looks amazing and exactly like the shape of the information I was hoping to receive. I'm pretty confident (misplaced or not) that I can make that work. I'll dig into it when I get a chance and let you know how I get on. 

Thank you!

2021-08-13 12:57 UTC, mikemonteith commented on CHANGELOG.md
> +- `PanelBlock`, `PanelList`, `GreyPanelBlock`, `PromoBlock`, `PromoGroupBlock` have been removed from the plugin, so references to these in your project will need to be removed in order to upgrade. E
Thanks @dragon-dxw please do get in touch with us by opening an issue if you want any help with the upgrade or things aren't clear.

2021-08-13 12:58 UTC, mikemonteith approved these changes

2021-08-13 12:58 UTC, merged